name: Build

on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: CI tasks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install codecov
        run: npm install codecov
      - name: Build
        run: npm run build
      - name: tests
        run: npm run test
      - name: Lint
        run: npm run lint